version: '3.9'

services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
  db-migrations:
    image: migrate/migrate:latest
    environment:
      - DB_PASSWORD=qwerty
    env_file:
      - ./.env
    volumes:
      - ./schema:/migrations
    command: sh -c "./wait-for-postgres.sh postgres; /db-migrations" && [ "-path", "/migrations/", "-database",  "postgres://postgres:qwerty@postgres:5432/postgres?sslmode=disable", "up" ]
    depends_on:
      - postgres
  app:
    build:
      context: ./library
      dockerfile: Dockerfile
    command: sh -c "./wait-for-postgres.sh postgres; ./app"
    ports:
      - 80:80
    depends_on:
      - db-migrations
    environment:
      - DB_PASSWORD=qwerty
      
  mongo:
    restart: always
    image: mongo:5.0.4
    volumes:
      - './.database/mongo/data:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=g0langn1nja
    ports:
      - 27017:27017
  logger:
    build:
      context: ./logger
      dockerfile: Dockerfile
    ports:
      - 81:81
    depends_on:
      - mongo
