# https://taskfile.dev/#/installation
version: '3'

silent: true

tasks:
  default:
    desc: Lint code
    cmds:
      - task: tidy
      - task: fmt
      - task: lint

  download:
    desc: Download external modules
    cmds:
      - echo "Download..."
      - GO111MODULE=on go mod download

  tidy:
    cmds:
      - echo "Tidy..."
      - GO111MODULE=on go mod tidy

  fmt:
    cmds:
      - echo "Fmt..."
      - gofmt -w .

  lint:
    cmds:
      - echo "Lint..."
      - golangci-lint run
  
  test:
    desc: Run testing - unit, integration, coverage
    cmds:
      - task: test-unit
      - task: test-integration
      - task: test-coverage
  
  test-unit:
    cmds:
      - env GO111MODULE=on go test --short -race -coverprofile=cover.out -v ./...

  test-integration:
    cmds:
      - newman run postman/api.postman_collection.json

  test-coverage:
    cmds:
      - env GO111MODULE=on go tool cover -func=cover.out

  bench:
    desc: Benchmarking
    cmds:
      - env GO111MODULE=on go test -bench=. -cpu=8 -benchmem -cpuprofile=cpu.out -memprofile=mem.out .
  
  run:
    desc: Run app and database in docker-compose
    cmds:
      - docker-compose up --build
  
  down:
    desc: Stop app in docker-compose
    cmds:
      - docker-compose down
