UPDATE schema_migrations SET dirty = false;

DROP TABLE IF EXISTS lists_items CASCADE;

DROP TABLE IF EXISTS users_lists CASCADE;

DROP TABLE IF EXISTS todo_lists CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS todo_items CASCADE;
